DA_QLNhanSu/Controllers/LuongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_QLNhanSu.Models;

namespace DA_QLNhanSu.Controllers
{
    public class LuongController : Controller
    {
        private readonly QLNhanSuContext _context;

        public LuongController(QLNhanSuContext context)
        {
            _context = context;
        }

        // GET: Luong
        public async Task<IActionResult> Index()
        {
            var qLNhanSuContext = _context.TblLuongs.Include(t => t.MaCmNavigation).Include(t => t.MaDvNavigation).Include(t => t.MaTdNavigation);
            return View(await qLNhanSuContext.ToListAsync());
        }

        // GET: Luong/Details/:id
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblLuong = await _context.TblLuongs
                .Include(t => t.MaCmNavigation)
                .Include(t => t.MaDvNavigation)
                .Include(t => t.MaTdNavigation)
                .FirstOrDefaultAsync(m => m.MaLuong == id);
            if (tblLuong == null)
            {
                return NotFound();
            }

            return View(tblLuong);
        }

        // GET: Luong/Create
        public IActionResult Create()
        {
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm");
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "TenDv");
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo");
            return View();
        }

        // POST: Luong/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaLuong,MaCm,MaTd,MaDv,LuongCoBan,LuongCbmoi,NgayNhap,NgaySua,GhiChu")] TblLuong tblLuong)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblLuong);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm", tblLuong.MaCm);
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "TenDv", tblLuong.MaDv);
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo", tblLuong.MaTd);
            return View(tblLuong);
        }

        // GET: Luong/Edit/:id
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblLuong = await _context.TblLuongs.FindAsync(id);
            if (tblLuong == null)
            {
                return NotFound();
            }
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm", tblLuong.MaCm);
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "TenDv", tblLuong.MaDv);
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo", tblLuong.MaTd);
            return View(tblLuong);
        }

        // POST: Luong/Edit/:id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaLuong,MaCm,MaTd,MaDv,LuongCoBan,LuongCbmoi,NgayNhap,NgaySua,GhiChu")] TblLuong tblLuong)
        {
            if (id != tblLuong.MaLuong)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblLuong);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblLuongExists(tblLuong.MaLuong))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm", tblLuong.MaCm);
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "TenDv", tblLuong.MaDv);
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo", tblLuong.MaTd);
            return View(tblLuong);
        }

        // GET: Luong/Delete/:id
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblLuong = await _context.TblLuongs
                .Include(t => t.MaCmNavigation)
                .Include(t => t.MaDvNavigation)
                .Include(t => t.MaTdNavigation)
                .FirstOrDefaultAsync(m => m.MaLuong == id);
            if (tblLuong == null)
            {
                return NotFound();
            }

            return View(tblLuong);
        }

        // POST: Luong/Delete/:id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblLuong = await _context.TblLuongs.FindAsync(id);
            _context.TblLuongs.Remove(tblLuong);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblLuongExists(int id)
        {
            return _context.TblLuongs.Any(e => e.MaLuong == id);
        }
    }
}

DA_QLNhanSu/Controllers/NhanVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_QLNhanSu.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using OfficeOpenXml;

namespace DA_QLNhanSu.Controllers
{
    public class NhanVienController : Controller
    {
        private readonly QLNhanSuContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public NhanVienController(QLNhanSuContext context,
            IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: NhanVien
        public async Task<IActionResult> Index()
        {
            var qLNhanSuContext = _context.TblTtnhanViens.Include(t => t.MaBhxhNavigation).Include(t => t.MaCmNavigation).Include(t => t.MaDvNavigation).Include(t => t.MaLuongNavigation).Include(t => t.MaTdNavigation).Include(t => t.MaThueNavigation);
            return View(await qLNhanSuContext.ToListAsync());
        }

        // GET: NhanVien
        public async Task<IActionResult> PhanQuyen()
        {
            var qLNhanSuContext = _context.TblTtnhanViens.Include(t => t.MaBhxhNavigation).Include(t => t.MaCmNavigation).Include(t => t.MaDvNavigation).Include(t => t.MaLuongNavigation).Include(t => t.MaTdNavigation).Include(t => t.MaThueNavigation);
            return View(await qLNhanSuContext.ToListAsync());
        }


        // GET: NhanVien/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblTtnhanVien = await _context.TblTtnhanViens
                .Include(t => t.MaBhxhNavigation)
                .Include(t => t.MaCmNavigation)
                .Include(t => t.MaDvNavigation)
                .Include(t => t.MaLuongNavigation)
                .Include(t => t.MaTdNavigation)
                .Include(t => t.MaThueNavigation)
                .FirstOrDefaultAsync(m => m.MaNv == id);
            if (tblTtnhanVien == null)
            {
                return NotFound();
            }

            return View(tblTtnhanVien);
        }

        public async Task<IActionResult> ExportToExcel()
        {
            // Lấy dữ liệu từ Entity Framework
            var data = await _context.TblTtnhanViens
                    .Include(t => t.MaBhxhNavigation)
                    .Include(t => t.MaCmNavigation)
                    .Include(t => t.MaDvNavigation)
                    .Include(t => t.MaLuongNavigation)
                    .Include(t => t.MaTdNavigation)
                    .Include(t => t.MaThueNavigation)
                    .ToListAsync();

            // Tạo một file Excel mới
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using var package = new ExcelPackage();
            // Tạo một worksheet mới
            var worksheet = package.Workbook.Worksheets.Add("Customers");

            // Thêm tiêu đề cho các cột
            worksheet.Cells[1, 1].Value = "STT";
            worksheet.Cells[1, 2].Value = "Mã NV";
            worksheet.Cells[1, 3].Value = "Họ Tên";
            worksheet.Cells[1, 4].Value = "Email";
            worksheet.Cells[1, 5].Value = "Phone";
            worksheet.Cells[1, 6].Value = "Ngày Sinh";
            worksheet.Cells[1, 7].Value = "Giới Tính";
            worksheet.Cells[1, 8].Value = "CMND";
            worksheet.Cells[1, 9].Value = "Nơi Sinh";
            worksheet.Cells[1, 10].Value = "Địa Chỉ";
            worksheet.Cells[1, 11].Value = "Dân Tộc";
            worksheet.Cells[1, 12].Value = "Tôn Giáo";
            worksheet.Cells[1, 13].Value = "Quốc Tịch";
            worksheet.Cells[1, 14].Value = "Trình Độ";
            worksheet.Cells[1, 15].Value = "Chuyên Môn";
            worksheet.Cells[1, 16].Value = "Đơn Vị";
            worksheet.Cells[1, 17].Value = "Nơi Đăng Ký BH";
            worksheet.Cells[1, 18].Value = "Cơ Quan QL Thuế";
            worksheet.Cells[1, 19].Value = "Lương Cơ Bản";
            worksheet.Cells[1, 20].Value = "Ghi Chú";

            // Thêm dữ liệu vào các cột
            for (int i = 0; i < data.Count; i++)
            {
                worksheet.Cells[i + 2, 1].Value = i + 1;
                worksheet.Cells[i + 2, 2].Value = data[i].MaNv;
                worksheet.Cells[i + 2, 3].Value = data[i].HoTen;
                worksheet.Cells[i + 2, 4].Value = data[i].Email;
                worksheet.Cells[i + 2, 5].Value = data[i].Sdt;
                worksheet.Cells[i + 2, 6].Value = data[i].NgaySinh;
                worksheet.Cells[i + 2, 7].Value = data[i].GioiTinh;
                worksheet.Cells[i + 2, 8].Value = data[i].Cmnd;
                worksheet.Cells[i + 2, 9].Value = data[i].NoiSinh;
                worksheet.Cells[i + 2, 10].Value = data[i].DiaChi;
                worksheet.Cells[i + 2, 11].Value = data[i].DanToc;
                worksheet.Cells[i + 2, 12].Value = data[i].TonGiao;
                worksheet.Cells[i + 2, 13].Value = data[i].QuocTich;
                worksheet.Cells[i + 2, 14].Value = data[i].MaTdNavigation.TenTrinhDo;
                worksheet.Cells[i + 2, 15].Value = data[i].MaCmNavigation.TenCm;
                worksheet.Cells[i + 2, 16].Value = data[i].MaDvNavigation.TenDv;
                worksheet.Cells[i + 2, 17].Value = data[i].MaBhxhNavigation.NoiDkkcb;
                worksheet.Cells[i + 2, 18].Value = data[i].MaThueNavigation.CoQuanQuanLyThue;
                worksheet.Cells[i + 2, 19].Value = data[i].MaLuongNavigation.LuongCoBan;
                worksheet.Cells[i + 2, 20].Value = data[i].GhiChu;
            }

            // Save file Excel
            var stream = new MemoryStream();
            package.SaveAs(stream);

            // Trả về file Excel như một phản hồi HTTP
            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "NhanVien_All.xlsx");
        }

        // GET: NhanVien/Create
        public IActionResult Create()
        {
            ViewData["MaBhxh"] = new SelectList(_context.TblBaoHiemXhs, "MaBhxh", "NoiDkkcb");
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm");
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "TenDv");
            ViewData["MaLuong"] = new SelectList(_context.TblLuongs, "MaLuong", "LuongCoBan");
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo");
            ViewData["MaThue"] = new SelectList(_context.TblThueThuNhapCaNhans, "MaThue", "CoQuanQuanLyThue");
            return View();
        }

        // POST: NhanVien/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TblTtnhanVien tblTtnhanVien)
        {
            if (ModelState.IsValid)
            {
                if (tblTtnhanVien.ConvertPhoto != null)
                {
                    string folder = "images/avatar";
                    folder += Guid.NewGuid().ToString() + "_" + tblTtnhanVien.ConvertPhoto.FileName;
                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);
                    await tblTtnhanVien.ConvertPhoto.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    tblTtnhanVien.Anh = $"/{folder}";
                }
                _context.Add(tblTtnhanVien);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaBhxh"] = new SelectList(_context.TblBaoHiemXhs, "MaBhxh", "MaBhxh", tblTtnhanVien.MaBhxh);
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm", tblTtnhanVien.MaCm);
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "MaDv", tblTtnhanVien.MaDv);
            ViewData["MaLuong"] = new SelectList(_context.TblLuongs, "MaLuong", "MaLuong", tblTtnhanVien.MaLuong);
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo", tblTtnhanVien.MaTd);
            ViewData["MaThue"] = new SelectList(_context.TblThueThuNhapCaNhans, "MaThue", "MaThue", tblTtnhanVien.MaThue);
            return View(tblTtnhanVien);
        }

        // GET: NhanVien/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblTtnhanVien = await _context.TblTtnhanViens.FindAsync(id);
            if (tblTtnhanVien == null)
            {
                return NotFound();
            }
            ViewData["MaBhxh"] = new SelectList(_context.TblBaoHiemXhs, "MaBhxh", "NoiDkkcb", tblTtnhanVien.MaBhxh);
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm", tblTtnhanVien.MaCm);
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "TenDv", tblTtnhanVien.MaDv);
            ViewData["MaLuong"] = new SelectList(_context.TblLuongs, "MaLuong", "LuongCoBan", tblTtnhanVien.MaLuong);
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo", tblTtnhanVien.MaTd);
            ViewData["MaThue"] = new SelectList(_context.TblThueThuNhapCaNhans, "MaThue", "CoQuanQuanLyThue", tblTtnhanVien.MaThue);
            return View(tblTtnhanVien);
        }

        // POST: NhanVien/Edit/:id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  TblTtnhanVien tblTtnhanVien)
        {
            if (id != tblTtnhanVien.MaNv)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (tblTtnhanVien.ConvertPhoto != null)
                {
                    string folder = "images/avatar";

DA_QLNhanSu/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Quản Lý Nhân Sự DNU";
}

<div class="text-center">
    

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 mb-2">
            <div class="card p-3">
                <div class="d-flex flex-row mb-3">
                    <img src="~/assets/img/icon_theme_menu/analytics.png" width="70">
                    <div class="d-flex flex-column ml-2"><span>Thống Kê Lương</span><span class="text-black-50">Xem danh sách bảng lương</span>
                    </div>
                </div>
                <h6>Danh sách tổng hợp bảng lương theo tháng của nhân viên công ty.</h6>
                <a asp-action="Index" asp-controller="ThongKeLuong" class="collapse-item">
                    <div class="d-flex justify-content-between install mt-3">
                        <span class="text-primary">Xem ngay&nbsp;<i class="fa fa-angle-right"></i></span>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4 mb-2">
            <div class="card p-3">
                <div class="d-flex flex-row mb-3">
                    <img src="~/assets/img/icon_theme_menu/salary.png" width="70">
                    <div class="d-flex flex-column ml-2">
                        <span>Bậc Lương</span><span class="text-black-50">Xem danh sách bậc lương</span>
                    </div>
                </div>
                <h6>Danh sách các bậc lương của nhân viên công ty.</h6>
                <a asp-controller="Luong" asp-action="Index" class="collapse-item">
                    <div class="d-flex justify-content-between install mt-3">
                        <span class="text-primary">Xem ngay&nbsp;<i class="fa fa-angle-right"></i></span>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4 mb-2">
            <div class="card p-3">
                <div class="d-flex flex-row mb-3">
                    <img src="~/assets/img/icon_theme_menu/taxes.png" width="70">
                    <div class="d-flex flex-column ml-2">
                        <span>Thuế TNCN</span><span class="text-black-50">Thuế thu nhập cá nhân</span>
                    </div>
                </div>
                <h6>Danh sách thuế thu nhập cá nhân của nhân viên công ty.</h6>
                <a asp-controller="ThueThuNhapCaNhan" asp-action="Index" class="collapse-item">
                    <div class="d-flex justify-content-between install mt-3">
                        <span class="text-primary">Xem ngay&nbsp;<i class="fa fa-angle-right"></i></span>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4 mb-2">
            <div class="card p-3">
                <div class="d-flex flex-row mb-3">
                    <img src="~/assets/img/icon_theme_menu/steward.png" width="70">
                    <div class="d-flex flex-column ml-2">
                        <span>Nhân Sự</span><span class="text-black-50">Nhân sự của công ty</span>
                    </div>
                </div>
                <h6>Danh sách nhân viên của công ty.</h6>
                <a asp-controller="NhanVien" asp-action="Index" class="collapse-item">
                    <div class="d-flex justify-content-between install mt-3">
                        <span class="text-primary">Xem ngay&nbsp;<i class="fa fa-angle-right"></i></span>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4 mb-2">
            <div class="card p-3">
                <div class="d-flex flex-row mb-3">
                    <img src="~/assets/img/icon_theme_menu/health-insurance.png" width="70">
                    <div class="d-flex flex-column ml-2">
                        <span>Bảo hiểm</span><span class="text-black-50">Bảo hiểm lao động</span>
                    </div>
                </div>
                <h6>Danh sách nhân các loại bảo hiểm lao động của công ty.</h6>
                <a asp-controller="BaoHiemXh" asp-action="Index" class="collapse-item">
                    <div class="d-flex justify-content-between install mt-3">
                        <span class="text-primary">Xem ngay&nbsp;<i class="fa fa-angle-right"></i></span>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4 mb-2">
            <div class="card p-3">
                <div class="d-flex flex-row mb-3">
                    <img src="~/assets/img/icon_theme_menu/settings.png" width="70">
                    <div class="d-flex flex-column ml-2">
                        <span>Phân Quyền</span><span class="text-black-50">Phân quyền cho các tài khoản</span>
                    </div>
                </div>
                <h6>Phân loại quyền truy cập và chức năng của các tài khoản.</h6>
                <a asp-action="Details" asp-controller="UserDashboard" class="collapse-item">
                    <div class="d-flex justify-content-between install mt-3">
                        <span class="text-primary">Xem ngay&nbsp;<i class="fa fa-angle-right"></i></span>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4 mb-2">
            <div class="card p-3">
                <div class="d-flex flex-row mb-3">
                    <img src="~/assets/img/icon_theme_menu/profile.png" width="70">
                    <div class="d-flex flex-column ml-2">
                        <span>Profile</span><span class="text-black-50">Thông tin tài khoản</span>
                    </div>
                </div>
                <h6>Xem, sửa thông tin cá nhân hoặc đổi mật khẩu tài khoản.</h6>
                <a asp-controller="NhanVien" asp-action="PhanQuyen" class="collapse-item">
                    <div class="d-flex justify-content-between install mt-3">
                        <span class="text-primary">Xem ngay&nbsp;<i class="fa fa-angle-right"></i></span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

DA_QLNhanSu/Views/Home/Login.cshtml
@model DA_QLNhanSu.Models.TblTtnhanVien
@{
    ViewData["Title"] = "Login";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://th.bing.com/th/id/R.c0c19473f9df9c0e1edbf4cd19e771ab?rik=EtkZNmbleCcFgQ&riu=http%3a%2f%2ftuyensinh.dainam.edu.vn%2fpic%2fSystemWebsite%2flogo-dai-nam636892871188011602.jpg&ehk=xtEg1U2SM9tf3Eg5wukFnfLjHZgz89k5hPQnMi%2fTszA%3d&risl=&pid=ImgRaw&r=0" rel="icon">
    <title>Login</title>
    <link href="~/assets/js/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/js/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/ruang-admin.min.css" rel="stylesheet">
</head>

<body class="bg-gradient-login">
    <!-- Login Content -->
    <div class="container-login">
        <div class="row justify-content-center">
            <div class="col-xl-6 col-lg-12 col-md-9">
                <div class="card shadow-sm my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="login-form">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4"><b>ĐĂNG NHẬP</b></h1>
                                    </div>
                                    <form asp-action="Login" class="user">
                                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                        <div class="form-group">
                                            <input asp-for="Email" type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp"
                                                   placeholder="Enter Email Address">
                                        </div>
                                        <div class="form-group">
                                            <input asp-for="Password" type="password" class="form-control" id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small" style="line-height: 1.5rem;">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">
                                                    Nhớ mật khẩu
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-block">Đăng nhập</button>
                                        </div>
                                        <hr>
                                        <a href="index.html" class="btn btn-google btn-block">
                                            <i class="fab fa-google fa-fw"></i> Đăng nhập với Google
                                        </a>
                                        <a href="index.html" class="btn btn-facebook btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Đăng nhập với Facebook
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="font-weight-bold small" asp-action="Register" asp-controller="Home">Tạo tài khoản mới</a>
                                    </div>
                                    <div class="text-center">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/assets/js/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/js/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/assets/js/ruang-admin.min.js"></script>
</body>
</html>