DA_QLNhanSu/Controllers/HomeNVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_QLNhanSu.Models;
using Microsoft.AspNetCore.Http;

namespace DA_QLNhanSu.Controllers
{
    public class HomeNVController : Controller
    {
        private readonly QLNhanSuContext _context;

        public HomeNVController(QLNhanSuContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> ThueCaNhan()
        {
            var SessionUserId = HttpContext.Session.GetString("MaNV");
            var id = int.Parse(SessionUserId);
            var user = await _context.TblTtnhanViens
                .Include(t => t.MaCmNavigation)
                .Include(t => t.MaDvNavigation)
                .Include(t => t.MaTdNavigation)
                .Include(t => t.MaBhxhNavigation)
                .Include(t => t.MaThueNavigation)
                .Include(t => t.MaLuongNavigation)
                .FirstOrDefaultAsync(m => m.MaNv == id);
            return View(user);
        }

        public async Task<IActionResult> ThongKeLuongChiTiet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblThongKeLuong = await _context.TblThongKeLuongs
                .Include(t => t.MaNvNavigation)
                .Include(t => t.MaThangNavigation)
                .FirstOrDefaultAsync(m => m.MaTkluong == id);
            if (tblThongKeLuong == null)
            {
                return NotFound();
            }

            return View(tblThongKeLuong);
        }

        public async Task<IActionResult> ThongTinBaoHiem()
        {
            var SessionUserId = HttpContext.Session.GetString("MaNV");
            var id = int.Parse(SessionUserId);
            var user = await _context.TblTtnhanViens
                .Include(t => t.MaCmNavigation)
                .Include(t => t.MaDvNavigation)
                .Include(t => t.MaTdNavigation)
                .Include(t => t.MaBhxhNavigation)
                .Include(t => t.MaThueNavigation)
                .Include(t => t.MaLuongNavigation)
                .FirstOrDefaultAsync(m => m.MaDv == id);
            return View(user);
        }

        public async Task<IActionResult> ThongKeLuong()
        {
            var SessionUserId = HttpContext.Session.GetString("MaNV");
            var id = int.Parse(SessionUserId);
            var thongKeLuongs = await _context.TblThongKeLuongs.Where(tkl => tkl.MaNv == id)
                                .Include(t => t.MaNvNavigation)
                                .Include(t => t.MaThangNavigation)
                                .ToListAsync();
            return View(thongKeLuongs);
        }
    }
}

DA_QLNhanSu/Controllers/UserDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_QLNhanSu.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace DA_QLNhanSu.Controllers
{
    public class UserDashboardController : Controller
    {
        private readonly QLNhanSuContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public UserDashboardController(QLNhanSuContext context,
            IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: UserDashboard/Details
        public async Task<IActionResult> Details()
        {
            var SessionUserId = HttpContext.Session.GetString("MaNV");
            var id = int.Parse(SessionUserId);
            var user = await _context.TblTtnhanViens
                .Include(t => t.MaCmNavigation)
                .Include(t => t.MaDvNavigation)
                .Include(t => t.MaTdNavigation)
                .Include(t => t.MaBhxhNavigation)
                .Include(t => t.MaThueNavigation)
                .Include(t => t.MaLuongNavigation)
                .FirstOrDefaultAsync(m => m.MaNv == id);
            return View(user);
        }

        // GET: UserDashboard/Edit/:id
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblTtnhanVien = await _context.TblTtnhanViens.FindAsync(id);
            if (tblTtnhanVien == null)
            {
                return NotFound();
            }
            ViewData["MaBhxh"] = new SelectList(_context.TblBaoHiemXhs, "MaBhxh", "MaBhxh", tblTtnhanVien.MaBhxh);
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm", tblTtnhanVien.MaCm);
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "MaDv", tblTtnhanVien.MaDv);
            ViewData["MaLuong"] = new SelectList(_context.TblLuongs, "MaLuong", "MaLuong", tblTtnhanVien.MaLuong);
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo", tblTtnhanVien.MaTd);
            ViewData["MaThue"] = new SelectList(_context.TblThueThuNhapCaNhans, "MaThue", "MaThue", tblTtnhanVien.MaThue);
            return View(tblTtnhanVien);
        }

        // POST: UserDashboard/Edit/:id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TblTtnhanVien tblTtnhanVien)
        {
            if (id != tblTtnhanVien.MaNv)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if(tblTtnhanVien.ConvertPhoto != null)
                {
                    string folder = "images/avatar";
                    folder += Guid.NewGuid().ToString()+"_"+ tblTtnhanVien.ConvertPhoto.FileName;
                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);
                    await tblTtnhanVien.ConvertPhoto.CopyToAsync(new FileStream(serverFolder,FileMode.Create));
                    tblTtnhanVien.Anh = $"/{folder}";
                }
                else // giữ nguyên giá trị của thuộc tính Anh
                {
                    tblTtnhanVien.Anh = _context.TblTtnhanViens.AsNoTracking().FirstOrDefault(x => x.MaNv == tblTtnhanVien.MaNv)?.Anh;
                }
                try
                {
                    _context.Update(tblTtnhanVien);
                    await _context.SaveChangesAsync();

                    HttpContext.Session.Remove("TenNV");
                    HttpContext.Session.SetString("TenNV", tblTtnhanVien.HoTen.ToString());
                    if (tblTtnhanVien.Anh != null)
                    {
                        HttpContext.Session.Remove("Image");
                        HttpContext.Session.SetString("Image", tblTtnhanVien.Anh.ToString());
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblTtnhanVienExists(tblTtnhanVien.MaNv))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details");
            }
            ViewData["MaBhxh"] = new SelectList(_context.TblBaoHiemXhs, "MaBhxh", "MaBhxh", tblTtnhanVien.MaBhxh);
            ViewData["MaCm"] = new SelectList(_context.TblChuyenMons, "MaCm", "TenCm", tblTtnhanVien.MaCm);
            ViewData["MaDv"] = new SelectList(_context.TblDonVis, "MaDv", "MaDv", tblTtnhanVien.MaDv);
            ViewData["MaLuong"] = new SelectList(_context.TblLuongs, "MaLuong", "MaLuong", tblTtnhanVien.MaLuong);
            ViewData["MaTd"] = new SelectList(_context.TblTrinhDos, "MaTd", "TenTrinhDo", tblTtnhanVien.MaTd);
            ViewData["MaThue"] = new SelectList(_context.TblThueThuNhapCaNhans, "MaThue", "MaThue", tblTtnhanVien.MaThue);
            return View(tblTtnhanVien);
        }

        public IActionResult ChangPassWord()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangPassWord(string oldPassword, string newPassword, string cfPassword)
        {
            var SessionUserId = HttpContext.Session.GetString("MaNV");
            var id = int.Parse(SessionUserId);
            var nhanVien = await _context.TblTtnhanViens.FindAsync(id);
            if (nhanVien != null) { 
            if (oldPassword == null)
            {
                ModelState.AddModelError("", "Mật khẩu không được để trống");
                return View();
            }
            if (newPassword == null)
            {
                ModelState.AddModelError("", "Mật khẩu không được để trống");
                return View();
            }
            if (cfPassword == null)
            {
                ModelState.AddModelError("", "Mật khẩu không được để trống");
                return View();
            }
            if(nhanVien.Password == oldPassword)
                {
                    if (newPassword == cfPassword)
                    {
                        nhanVien.Password = newPassword;
                        _context.Update(nhanVien);
                        var check = _context.SaveChanges();
                        if (check > 0)
                        {
                            return RedirectToAction("Details");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Lỗi lưu dữ liệu");
                            return View();
                        }

                    } else
                    {
                        ModelState.AddModelError("", "Mật khẩu nhập lại không khớp");
                        return View();
                    }

                }
                else
                {
                    ModelState.AddModelError("", "Mật khẩu không chính xác");
                    return View();
                }
            } else return RedirectToAction("Login", "Home");
        }

        private bool TblTtnhanVienExists(int id)
        {
            return _context.TblTtnhanViens.Any(e => e.MaNv == id);
        }
    }
}

DA_QLNhanSu/Views/UserDashboard/ChangPassWord.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "ChangPassWord";
    Layout = null;
}
<title>@ViewData["Title"]</title>
<link href="~/assets/js/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link href="~/assets/js/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="~/assets/js/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="~/assets/css/ruang-admin.min.css" rel="stylesheet">
<script src="~/assets/js/vendor/jquery/jquery.min.js"></script>
<script src="~/assets/js/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/js/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="~/assets/js/ruang-admin.min.js"></script>
<script src="~/assets/js/vendor/datatables/jquery.dataTables.min.js"></script>
<div class="container p-4">
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Danh Sách Đơn Vị</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
        <li class="breadcrumb-item">Đơn Vị</li>
        <li class="breadcrumb-item active" aria-current="page">Sửa</li>
    </ol>
</div>

<div class="card mb-3">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h4 class="m-0 font-weight-bold text-primary">Đổi mật khẩu</h4>
    </div>
    <div class="card-body">
        <div class="form-group">
            <div class="card-body">
                <form method="post" asp-action="ChangPassWord" asp-controller="UserDashboard">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label for="oldPassword">Mật khẩu cũ:</label>
                        <input type="password" class="form-control" id="oldPassword" name="oldPassword">
                        <span id="oldPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="newPassword">Mật khẩu mới:</label>
                        <input type="password" class="form-control" id="newPassword" name="newPassword">
                        <span id="newPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="cfPassword">Xác nhận mật khẩu:</label>
                        <input type="password" class="form-control" id="cfPassword" name="cfPassword">
                        <span id="oldPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32("Role") == 1 || HttpContextAccessor.HttpContext.Session.GetInt32("Role") == 2)
                        {
                            <a asp-action="Index" asp-controller="Home" class="btn btn-secondary">Quay lại</a>
                        }
                        else
                        {
                            <a asp-action="ThueCaNhan" asp-controller="HomeNV" class="btn btn-secondary">Quay lại</a>
                        }
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

DA_QLNhanSu/Views/UserDashboard/Details.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@model DA_QLNhanSu.Models.TblTtnhanVien

@{
    ViewData["Title"] = "Thông tin cá nhân";
    Layout = null;
}
<title>@ViewData["Title"]</title>
<link href="~/assets/js/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link href="~/assets/js/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="~/assets/js/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="~/assets/css/ruang-admin.min.css" rel="stylesheet">
<script src="~/assets/js/vendor/jquery/jquery.min.js"></script>
<script src="~/assets/js/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/js/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="~/assets/js/ruang-admin.min.js"></script>
<script src="~/assets/js/vendor/datatables/jquery.dataTables.min.js"></script>
<div class="container p-4">
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thông tin cá nhân</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
        <li class="breadcrumb-item">Profile</li>
    </ol>
</div>

<div class="card mb-3">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h4 class="m-0 font-weight-bold text-primary">Xem thông tin</h4>
    </div>
    <form>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MaNv" />
        <div class="card-body row">
            <div class="form-group col-lg-12">
                <label class="control-label">Ảnh đại diện</label>
                <div class="text-center">
                    <img src="@Model.Anh" class="rounded" alt="@Model.HoTen" width="250">
                </div>
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Họ và tên</label>
                <input asp-for="HoTen" type="text" readonly class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Ngày sinh</label>
                <input asp-for="NgaySinh" type="date" readonly class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Chuyên môn</label>
                <input asp-for="MaCmNavigation.TenCm" readonly class="form-control" />
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Trình độ</label>
                <input asp-for="MaTdNavigation.TenTrinhDo" readonly class="form-control" />
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Đơn vị</label>
                <input asp-for="MaDvNavigation.TenDv" readonly class="form-control" />
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Lương cơ bản</label>
                <input asp-for="MaLuongNavigation.LuongCoBan" readonly class="form-control" />
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Thuế</label>
                <input asp-for="MaThueNavigation.CoQuanQuanLyThue" readonly class="form-control" />
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Bảo hiểm</label>
                <input asp-for="MaBhxhNavigation.NoiDkkcb" readonly class="form-control" />
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Dân tộc</label>
                <input asp-for="DanToc" type="text" readonly class="form-control" />
                <span asp-validation-for="DanToc" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Tôn giáo</label>
                <input asp-for="TonGiao" readonly type="text" class="form-control" />
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Quốc tịch</label>
                <input asp-for="QuocTich" readonly type="text" class="form-control" />
                <span asp-validation-for="QuocTich" class="text-danger"></span>

            </div>
            <div class="form-group col-lg-6">
                <label asp-for="Cmnd" class="control-label">Số CMND</label>
                <input asp-for="Cmnd" readonly class="form-control" />
                <span asp-validation-for="Cmnd" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6">
                <label asp-for="GioiTinh" class="control-label">Giới tính</label>
                <input asp-for="GioiTinh" readonly class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Điện thoại</label>
                <input asp-for="Sdt" readonly class="form-control" />
                <span asp-validation-for="Sdt" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-6">
                <label class="control-label">Email</label>
                <input asp-for="Email" readonly class="form-control" />
            </div>
            <div class="form-group col-lg-12">
                <label asp-for="NoiSinh" class="control-label">Nơi sinh</label>
                <input asp-for="NoiSinh" readonly class="form-control" />
                <span asp-validation-for="NoiSinh" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-12">
                <label asp-for="DiaChi" class="control-label">Địa chỉ</label>
                <input asp-for="DiaChi" readonly class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group col-lg-12">
                <label asp-for="GhiChu" class="control-label">Ghi chú</label>
                <textarea asp-for="GhiChu" readonly class="form-control"></textarea>
                <span asp-validation-for="GhiChu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Edit" asp-controller="UserDashboard" asp-route-id="@Model.MaNv" class="btn btn-primary">Sửa lại thông tin</a>
                <a asp-action="ChangPassWord" asp-controller="UserDashboard" class="btn btn-danger">Đổi mật khẩu</a>
                @if (HttpContextAccessor.HttpContext.Session.GetInt32("Role") == 1 || HttpContextAccessor.HttpContext.Session.GetInt32("Role") == 2)
                {
                    <a asp-action="Index" asp-controller="Home" class="btn btn-secondary">Quay lại</a>
                } else
                {
                    <a asp-action="ThueCaNhan" asp-controller="HomeNV" class="btn btn-secondary">Quay lại</a>
                }
            </div>
        </div>
    </form>
</div>
</div>

DA_QLNhanSu/Views/UserDashboard/Edit.cshtml
@model DA_QLNhanSu.Models.TblTtnhanVien
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Edit";
    Layout = null;
}
<title>@ViewData["Title"]</title>
<link href="~/assets/js/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<link href="~/assets/js/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="~/assets/js/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="~/assets/css/ruang-admin.min.css" rel="stylesheet">
<script src="~/assets/js/vendor/jquery/jquery.min.js"></script>
<script src="~/assets/js/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/js/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="~/assets/js/ruang-admin.min.js"></script>
<script src="~/assets/js/vendor/datatables/jquery.dataTables.min.js"></script>
<div class="container p-4">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Thông tin cá nhân</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">Profile</li>
            <li class="breadcrumb-item">Sửa</li>
        </ol>
    </div>

    <div class="card mb-3">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h4 class="m-0 font-weight-bold text-primary">Sửa thông tin</h4>
        </div>
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="card-body row">
                <input type="hidden" asp-for="MaNv" />
                <input type="hidden" asp-for="MaCm" />
                <input type="hidden" asp-for="MaTd" />
                <input type="hidden" asp-for="MaDv" />
                <input type="hidden" asp-for="MaThue" />
                <input type="hidden" asp-for="MaBhxh" />
                <input type="hidden" asp-for="MaLuong" />
                <input type="hidden" asp-for="Password" />
                <input type="hidden" asp-for="Email" />
                <input type="hidden" asp-for="PhanQuyen" />
                <div class="form-group col-lg-12">
                    <label asp-for="ConvertPhoto" class="control-label">Ảnh</label>
                    <div class="text-center mb-2">
                        <img src="@Model.Anh" class="rounded" alt="@Model.HoTen" width="250">
                    </div>
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input asp-for="ConvertPhoto" class="custom-file-input">
                            <label asp-for="ConvertPhoto" class="custom-file-label">Choose file</label>
                        </div>
                    </div>
                    <span asp-validation-for="ConvertPhoto" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="HoTen" class="control-label">Họ tên</label>
                    <input asp-for="HoTen" class="form-control" />
                    <span asp-validation-for="HoTen" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="NgaySinh" class="control-label">Ngày sinh</label>
                    <input asp-for="NgaySinh" type="date" class="form-control" />
                    <span asp-validation-for="NgaySinh" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="GioiTinh" class="control-label">Giới tính</label>
                    <select asp-for="GioiTinh" class="form-control">
                        <option value="">--Chọn giới tính--</option>
                        <option value="Nam">Nam</option>
                        <option value="Nữ">Nữ</option>
                    </select>
                    <span asp-validation-for="GioiTinh" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="Cmnd" class="control-label">Số CMND</label>
                    <input asp-for="Cmnd" class="form-control" />
                    <span asp-validation-for="Cmnd" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-12">
                    <label asp-for="NoiSinh" class="control-label">Nơi sinh</label>
                    <input asp-for="NoiSinh" class="form-control" />
                    <span asp-validation-for="NoiSinh" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-12">
                    <label asp-for="DiaChi" class="control-label">Địa chỉ</label>
                    <input asp-for="DiaChi" class="form-control" />
                    <span asp-validation-for="DiaChi" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="Sdt" class="control-label">Điện thoại</label>
                    <input asp-for="Sdt" class="form-control" />
                    <span asp-validation-for="Sdt" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="DanToc" class="control-label">Dân tộc</label>
                    <input asp-for="DanToc" class="form-control" />
                    <span asp-validation-for="DanToc" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="TonGiao" class="control-label">Tôn giáo</label>
                    <input asp-for="TonGiao" class="form-control" />
                    <span asp-validation-for="TonGiao" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-6">
                    <label asp-for="QuocTich" class="control-label">Quốc tịch</label>
                    <input asp-for="QuocTich" class="form-control" />
                    <span asp-validation-for="QuocTich" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-12">
                    <label asp-for="GhiChu" class="control-label">Ghi chú</label>
                    <textarea asp-for="GhiChu" class="form-control"></textarea>
                    <span asp-validation-for="GhiChu" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    @if (HttpContextAccessor.HttpContext.Session.GetInt32("Role") == 1 || HttpContextAccessor.HttpContext.Session.GetInt32("Role") == 2)
                    {
                        <a asp-action="Index" asp-controller="Home" class="btn btn-secondary">Quay lại</a>
                    }
                    else
                    {
                        <a asp-action="ThueCaNhan" asp-controller="HomeNV" class="btn btn-secondary">Quay lại</a>
                    }
                </div>
            </div>
        </form>
    </div>
</div>